# Ledger: General 

This notebook shows the general ledger for the LLC

In [1]:
# Load bookkeeping services
import os
from ledger.LLC import LLC
from pathlib import Path
import datetime
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

top = os.path.join(Path.home(), 'GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group')
llc = LLC('WBGroupLLC',debug=False, top=top)  # debug='details'

In [2]:
llc._Bank()

llc.bk.df.head(2)

,dt,amt,C2,CheckNo,desc,TransType,Acct,AcctSub,TDesc
0,2025.12.29,-177.0,*,NaN,Cash eWithdrawal in Branch 12/29/2025 13:47 PM...,Exp,Acct.Fixed.Tangible.InService,NaN,Property Purchase
1,2025.12.29,177.0,*,NaN,eDeposit in Branch 12/29/25 03:48:15 PM 14650 ...,Rev,Acct.Cash.Bank,NaN,Owner Investment

In [3]:
begBal = llc._assets()._BegBal

# 
dtReport = datetime.datetime.now().strftime('%Y.%m.%d')

display(Markdown(f"### Profile - {dtReport}"))
display(Markdown(f"- **LLC Name: {llc.objName}**"))
display(Markdown(f"- **Year: {llc.yr}**\nAcct.Equity.Cash Beginning Balance: {begBal}"))

### Profile - 2026.04.13

- **LLC Name: WBGroupLLC**

- **Year: 2025**
Acct.Equity.Cash Beginning Balance: <bound method llcAssets._BegBal of <ledger.llcAssets.llcAssets object at 0x1121e87d0>>

## Find New Bank Transactions against llcExpRev - newList

In [4]:

from ledger.llcBank import llcBank
from ledger.llcExpRev import llcExpRev
from ledger.ledgerGeneral import ledgerGeneral


bkObj = llc.bk
erObj = llcExpRev(llc)
gl = ledgerGeneral(llc)


newList = gl.findNewExpRevFromBank(bkObj, erObj)
display(Markdown(f"<h3> New Bank Transactions {len(newList)}"))

if len(newList) > 0 : 
    display(pd.DataFrame(newList))

llcBank : _mapLedger Failed mapping  acct:Acct.Fixed.Tangible.InService in mapLedgerDict, default
llcBank : _mapLedger Failed mapping  acct:Acct.Rev.Rent in mapLedgerDict, default
llcBank : _mapLedger Failed mapping  acct:Acct.Rev.Fees.Other in mapLedgerDict, default
llcBank : _mapLedger Failed mapping  acct:Acct.Rev.Fees.Other in mapLedgerDict, default
llcBank : _mapLedger Failed mapping  acct:Acct.Rev.Fees.Other in mapLedgerDict, default
llcBank : _mapLedger Failed mapping  acct:Acct.Rev.Rent in mapLedgerDict, default
llcBank : _mapLedger Failed mapping  acct:Acct.Rev.Rent in mapLedgerDict, default
llcBank : _mapLedger Failed mapping  acct:Acct.Fixed.Tangible.InService in mapLedgerDict, default

<h3> New Bank Transactions 53

,dt,desc,amt,aType,acct,Ledger,acctSub,propNm,propID,propAddr,propOwners,tID,tDB,refDB,refDoc,_unknown
0,2025.08.20,Owner investment,219000.00,Debit,Acct.Cash.Bank,"(Acct.Equity.Owner.Cash,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.08.20_219000.0,llcBank,llcBank,WT FED#02M03 NATIONAL FINANCIAL /ORG=FRANCIS X...,{}
1,2025.08.20,Owner Investment,50.00,Debit,Acct.Cash.Bank,"(Acct.Equity.Owner.Cash,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.08.20_50.0,llcBank,llcBank,WFB OPENING DEPOSIT FROM CARD XXXXXXXXXXXX1980...,{}
2,2025.08.26,Property Purchase,213936.95,Credit,Acct.Fixed.Tangible.InService,"(Acct.Ledger.Unknown,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.08.26_213936.95,llcBank,llcBank,WITHDRAWAL MADE IN A BRANCH/STORE,{}
3,2025.08.28,Approved Purchase,75.76,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.08.28_75.76,llcBank,llcBank,PURCHASE AUTHORIZED ON 08/27 AMAZON MKTPL*6Y5U...,{}
4,2025.08.28,Pay Monthly Util,250.00,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Elec,H_805HighMesa,NaN,NaN,NaN,2025.08.28_250.0,llcBank,llcBank,Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...,{}
5,2025.09.03,Pay Monthly Util,150.00,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Water,H_805HighMesa,NaN,NaN,NaN,2025.09.03_150.0,llcBank,llcBank,CHECK # 101,{}
6,2025.09.10,Approved Purchase,25.94,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.09.10_25.94,llcBank,llcBank,PURCHASE AUTHORIZED ON 09/10 Kings Feed And Ha...,{}
7,2025.09.22,Approved Purchase,38.94,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.09.22_38.94,llcBank,llcBank,PURCHASE AUTHORIZED ON 09/19 AMAZON MKTPL*B108...,{}
8,2025.09.29,Owner Investment,30.00,Debit,Acct.Cash.Bank,"(Acct.Equity.Owner.Cash,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.09.29_30.0,llcBank,llcBank,MOBILE DEPOSIT : REF NUMBER :409290718471,{}
9,2025.10.03,Approved Purchase,8.29,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.03_8.29,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/01 AMAZON MKTPL*NJ7X...,{}
10,2025.10.03,Approved Purchase,17.31,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.03_17.31,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/03 WIMBERLEY ACE WIM...,{}
11,2025.10.06,Approved Purchase,140.73,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.06_140.73,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/04 WAL-MART #0404 SA...,{}
12,2025.10.07,Pay Electrician Repair Outlet,50.00,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Util,H_805HighMesa,NaN,NaN,NaN,2025.10.07_50.0,llcBank,llcBank,CHECK # 102,{}
13,2025.10.07,Approved Purchase,31.86,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.07_31.86,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/06 LOWES #00907* 866...,{}
14,2025.10.07,Approved Purchase,14.06,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.07_14.06,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,{}
15,2025.10.07,Approved Purchase,27.04,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.07_27.04,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/07 LOWE'S #159 SAN M...,{}
16,2025.10.08,Return of materials,27.04,Debit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.08_27.04,llcBank,llcBank,PURCHASE RETURN AUTHORIZED ON 10/07 LOWES #001...,{}
17,2025.10.08,Approved Purchase,51.06,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.08_51.06,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,{}
18,2025.10.08,Approved Purchase,65.36,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.08_65.36,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/07 H-E-B #708 WIMBER...,{}
19,2025.10.08,Approved Purchase,34.63,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.08_34.63,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,{}
20,2025.10.09,Approved Purchase,14.06,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.09_14.06,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/08 WIMBERLEY ACE WIM...,{}
21,2025.10.09,Approved Purchase,37.87,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.09_37.87,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/08 WIMBERLEY ACE WIM...,{}
22,2025.10.10,Pay Monthly Util,72.50,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Elec,H_805HighMesa,NaN,NaN,NaN,2025.10.10_72.5,llcBank,llcBank,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,{}
23,2025.10.14,Approved Purchase,90.90,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.14_90.9,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/13 TEXAS DISPOSAL SY...,{}
24,2025.10.14,Approved Purchase,30.71,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.14_30.71,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/10 WIMBERLEY ACE WIM...,{}
25,2025.10.14,Approved Purchase,108.32,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.14_108.32,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/12 H-E-B #708 WIMBER...,{}
26,2025.10.14,Approved Purchase,19.47,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.14_19.47,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/13 AMAZON MKTPL*NM32...,{}
27,2025.10.16,Approved Purchase,60.58,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.16_60.58,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/16 Harbor Freight To...,{}
28,2025.10.17,Approved Purchase,57.31,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.17_57.31,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/16 SQ *RODCO STEEL D...,{}
29,2025.10.20,Pay Monthly Util,50.00,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Water,H_805HighMesa,NaN,NaN,NaN,2025.10.20_50.0,llcBank,llcBank,BILL PAY Water-COMWSC RECURRING 38 ON 10-20,{}
30,2025.10.22,Approved Purchase,36.09,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.22_36.09,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/22 WIMBERLEY ACE WIM...,{}
31,2025.10.22,"Repair Utility Outlet,Electrician",135.00,Credit,Acct.Exp.Repair,"(Acct.Cash.Bank,)",Maintenance,H_805HighMesa,NaN,NaN,NaN,2025.10.22_135.0,llcBank,llcBank,VENMO ADDFUNDS 251022 1045679339909 FRANCIS ROJAS,{}
32,2025.10.23,,1000.00,Debit,Acct.Rev.Rent,"(Acct.Ledger.Unknown,)",Income.Rent,H_805HighMesa,NaN,NaN,NaN,2025.10.23_1000.0,llcBank,llcBank,ZELLE FROM ALEJANDRO VILLARREAL ON 10/23 REF #...,{}
33,2025.10.24,Bank Promotion for account openning,400.00,Debit,Acct.Cash.Bank,"(Acct.Equity.Owner.Cash,)",Bank,H_805HighMesa,NaN,NaN,NaN,2025.10.24_400.0,llcBank,llcBank,Promotion Bonus,{}
34,2025.10.24,Customer payment setup,0.24,Debit,Acct.Rev.Fees.Other,"(Acct.Ledger.Unknown,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.24_0.24,llcBank,llcBank,TRUIST ACCTVERIFY 251024 15280212827 ALEJANDRO...,{}
35,2025.10.24,Customer payment setup,0.29,Debit,Acct.Rev.Fees.Other,"(Acct.Ledger.Unknown,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.24_0.29,llcBank,llcBank,TRUIST ACCTVERIFY 251024 15280212821 ALEJANDRO...,{}
36,2025.10.24,Customer payment setup,0.53,Credit,Acct.Rev.Fees.Other,"(Acct.Ledger.Unknown,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.10.24_0.53,llcBank,llcBank,TRUIST ACCTVERIFY 251024 15280212831 ALEJANDRO...,{}
37,2025.11.03,Approved Purchase,487.13,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.11.03_487.13,llcBank,llcBank,PURCHASE AUTHORIZED ON 10/31 LAIRD PLASTICS SA...,{}
38,2025.11.03,Approved Purchase,73.56,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.11.03_73.56,llcBank,llcBank,PURCHASE AUTHORIZED ON 11/02 AMAZON MKTPL*NK5P...,{}
39,2025.11.07,Approved Purchase,42.15,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.11.07_42.15,llcBank,llcBank,PURCHASE AUTHORIZED ON 11/06 SP GROWERS SOLUTI...,{}
40,2025.11.10,Pay Monthly Util,119.49,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Elec,H_805HighMesa,NaN,NaN,NaN,2025.11.10_119.49,llcBank,llcBank,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,{}
41,2025.11.12,,1500.00,Debit,Acct.Rev.Rent,"(Acct.Ledger.Unknown,)",Income.Rent,H_805HighMesa,NaN,NaN,NaN,2025.11.12_1500.0,llcBank,llcBank,ZELLE FROM NICOLA ROJAS ON 11/11 REF # BBT3482...,{}
42,2025.11.17,Approved Purchase,32.42,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.11.17_32.42,llcBank,llcBank,PURCHASE AUTHORIZED ON 11/14 SP GROWERS SOLUTI...,{}
43,2025.11.17,Approved Purchase,19.47,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.11.17_19.47,llcBank,llcBank,PURCHASE AUTHORIZED ON 11/15 AMAZON MKTPL*B80W...,{}
44,2025.11.17,Approved Purchase,30.00,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.11.17_30.0,llcBank,llcBank,PURCHASE AUTHORIZED ON 11/15 HAYS CO TX WIMBER...,{}
45,2025.11.17,Approved Purchase,2.00,Credit,Acct.Exp.Other,"(Acct.Cash.Bank,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.11.17_2.0,llcBank,llcBank,PURCHASE AUTHORIZED ON 11/15 HAYS CO TX WIMBER...,{}
46,2025.11.18,Pay Monthly Util,50.00,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Water,H_805HighMesa,NaN,NaN,NaN,2025.11.18_50.0,llcBank,llcBank,BILL PAY Water-COMWSC RECURRING 38 ON 11-18,{}
47,2025.12.01,,1500.00,Debit,Acct.Rev.Rent,"(Acct.Ledger.Unknown,)",Income.Rent,H_805HighMesa,NaN,NaN,NaN,2025.12.01_1500.0,llcBank,llcBank,ZELLE FROM NICOLA ROJAS ON 12/01 REF # BBT3528...,{}
48,2025.12.10,Pay Monthly Util,129.16,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Elec,H_805HighMesa,NaN,NaN,NaN,2025.12.10_129.16,llcBank,llcBank,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,{}
49,2025.12.18,Pay Monthly Util,50.00,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Water,H_805HighMesa,NaN,NaN,NaN,2025.12.18_50.0,llcBank,llcBank,BILL PAY Water-COMWSC RECURRING 38 ON 12-18,{}
50,2025.12.26,Pay Monthly Util,135.80,Credit,Acct.Exp.Util,"(Acct.Cash.Bank,)",Ins_Home,H_805HighMesa,NaN,NaN,NaN,2025.12.26_135.8,llcBank,llcBank,ALLSTATE IND CO INS PYMT DEC024 00000043853221...,{}
51,2025.12.29,Owner Investment,177.00,Debit,Acct.Cash.Bank,"(Acct.Equity.Owner.Cash,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.12.29_177.0,llcBank,llcBank,eDeposit in Branch 12/29/25 03:48:15 PM 14650 ...,{}
52,2025.12.29,Property Purchase,177.00,Credit,Acct.Fixed.Tangible.InService,"(Acct.Ledger.Unknown,)",NaN,H_805HighMesa,NaN,NaN,NaN,2025.12.29_177.0,llcBank,llcBank,Cash eWithdrawal in Branch 12/29/2025 13:47 PM...,{}

## Concatenate Bank New Transactions into llcExpRev - update DB

In [5]:
''' In Constructions: FIXME
- concatenate newList of bank transaction to llcExpRev transactions (erObj.load())
'''
_ = 0

## InConst : Merge llcAsset and llcExpRev

In [6]:
''' FIXME:
- add an llcBank method mergeToGL(aObj, erObj) that outputs a new tranaction list, method does the following:
- input list of bank transactions (bkObj.load()) and a list of llcExpRev tranactions dict (erObj.load()
- merge new bank transaction (not in erObj) into transaction list (format erObj transaction format)
'''
## InConst: method to convert ledgerDB object into GL list
from ledger.ledgerGeneral import ledgerGeneral
from ledger.llcExpRev import llcExpRev
from ledger.llcAssets import llcAssets


aObj = llcAssets(llc)
erObj = llcExpRev(llc)
gl = ledgerGeneral(llc)

In [14]:
#_aList = aObj.load()

erList = erObj.load()
aList = aObj.load()

acctKey = 'Acct.Rev'
revList = [tDict for tDict in erList if  acctKey in tDict['acct'] or acctKey in tDict['Ledger']]
print (f"aList: {len(aList)}, revList:{len(revList)}")

# Expand to double-entry GL pairs (drops Ledger, recomputes tID + acctType)
erList_gl = gl.toDoubleEntry(erList)
aList_gl = gl.toDoubleEntry(aList)

# Merge: resolve_dups=False → keep all, flag cross-source dups
glList = gl.mergeGL([erList_gl], resolve_dups=False)

pd.DataFrame(erList)

aList: 13, revList:0

,Ledger,aType,acct,acctSub,amt,desc,dt,propAddr,propID,propNm,propOwners,refDB,refDoc,tDB,tID,acctType,_unknown
0,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,75.76,NoRcp: Approved Purchase: AMAZON MKTPL*6Y5UJ A...,2025.08.28,None,None,H_805HighMesa,None,llcBank,PURCHASE AUTHORIZED ON 08/27 AMAZON MKTPL*6Y5U...,llcBank,2025.08.28_75.76,Expense,NaN
1,Acct.Cash.Bank,Debit,Acct.Exp.Util,Elec,250.00,Auto: Pay Monthly Util,2025.08.28,None,None,H_805HighMesa,None,llcBank,Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...,llcBank,2025.08.28_250.0,Expense,NaN
2,Acct.Cash.Bank,Debit,Acct.Exp.Util,Water,150.00,Auto: Pay Monthly Util,2025.09.03,None,None,H_805HighMesa,None,llcBank,CHECK # 101,llcBank,2025.09.03_150.0,Expense,NaN
3,Acct.Cash.Bank,Debit,Acct.Exp.Other,,25.94,Receipt+ Approved Purchase: Kings Feed And Har...,2025.09.10,,,H_805HighMesa,,llcBank,PURCHASE AUTHORIZED ON 09/10 Kings Feed And Ha...,llcBank,2025.09.10_25.94,Expense,
4,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,38.94,NoRecpt Approved Purchase: AMAZON MKTPL*B108S ...,2025.09.22,None,None,H_805HighMesa,None,llcBank,PURCHASE AUTHORIZED ON 09/19 AMAZON MKTPL*B108...,llcBank,2025.09.22_38.94,Expense,NaN
5,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,8.29,NoRcpt Approved Purchase: AMAZON MKTPL*NJ7XX A...,2025.10.03,None,None,H_805HighMesa,None,llcBank,PURCHASE AUTHORIZED ON 10/01 AMAZON MKTPL*NJ7X...,llcBank,2025.10.03_8.29,Expense,NaN
6,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,17.31,NoRcpt Approved Purchase: WIMBERLEY ACE WIMBER...,2025.10.03,None,None,H_805HighMesa,None,llcBank,PURCHASE AUTHORIZED ON 10/03 WIMBERLEY ACE WIM...,llcBank,2025.10.03_17.31,Expense,NaN
7,Acct.Cash.Bank,Debit,Acct.Exp.Repair,Repair,50.00,EPay Pay Electrician Repair Outlet,2025.10.07,None,None,H_805HighMesa,None,llcBank,CHECK # 102,llcBank,2025.10.07_50.0,Expense,NaN
8,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,31.86,NoRcpt Approved Purchase: LOWES #00907* 866-48...,2025.10.07,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/06 LOWES #00907* 866...,llcBank,2025.10.07_31.86,Expense,NaN
9,Acct.Cash.Bank,Debit,Acct.Exp.Repair,Repair,14.06,Recpt Approved Purchase - ACE Garbage Disposal...,2025.10.07,,e20250826-805HMD,H_805HighMesa,,llcBank,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,llcBank,2025.10.07_14.06,Expense,NaN
10,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,27.04,NoRcpt Approved Purchase: LOWE'S #159 SAN MARCOS,2025.10.07,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/07 LOWE'S #159 SAN M...,llcBank,2025.10.07_27.04,Expense,NaN
11,Acct.Cash.Bank,Debit,Acct.Exp.Util,Waste,90.90,Auto: Approved Purchase: TEXAS DISPOSAL SYS 80...,2025.10.14,,e20250826-805HMD,H_805HighMesa,,llcBank,PURCHASE AUTHORIZED ON 10/13 TEXAS DISPOSAL SY...,llcBank,2025.10.14_90.9,Expense,
12,Acct.Cash.Bank,Debit,Acct.Exp.Other,Celebration,65.36,NoRcpt Approved Purchase: H-E-B - celebration,2025.10.08,None,None,H_805HighMesa,None,llcBank,PURCHASE AUTHORIZED ON 10/07 H-E-B #708 WIMBER...,llcBank,2025.10.08_65.36,Expense,NaN
13,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,34.63,NoRcpt Approved Purchase: WIMBERLEY ACE WIMBER...,2025.10.08,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,llcBank,2025.10.08_34.63,Expense,NaN
14,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,14.06,NoRcpt Approved Purchase: WIMBERLEY ACE WIMBER...,2025.10.09,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/08 WIMBERLEY ACE WIM...,llcBank,2025.10.09_14.06,Expense,NaN
15,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,37.87,NoRcpt Approved Purchase: WIMBERLEY ACE WIMBER...,2025.10.09,None,None,RV_RV1a,None,llcBank,PURCHASE AUTHORIZED ON 10/08 WIMBERLEY ACE WIM...,llcBank,2025.10.09_37.87,Expense,NaN
16,Acct.Cash.Bank,Debit,Acct.Exp.Util,Elec,72.50,Pay Monthly Util,2025.10.10,None,None,H_805HighMesa,None,llcBank,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,llcBank,2025.10.10_72.5,Expense,NaN
17,Acct.Cash.Bank,Debit,Acct.Exp.Other,Waste,90.90,Approved Purchase: TEXAS DISPOSAL SYS 800-3758375,2025.10.14,None,None,H_805HighMesa,None,llcBank,PURCHASE AUTHORIZED ON 10/13 TEXAS DISPOSAL SY...,llcBank,2025.10.14_90.9,Expense,NaN
18,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,30.71,NoRcpt Approved Purchase: WIMBERLEY ACE WIMBER...,2025.10.14,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/10 WIMBERLEY ACE WIM...,llcBank,2025.10.14_30.71,Expense,NaN
19,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,108.32,NoRcpt Approved Purchase: H-E-B #708 WIMBERLEY TX,2025.10.14,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/12 H-E-B #708 WIMBER...,llcBank,2025.10.14_108.32,Expense,NaN
20,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,19.47,NoRcpt Approved Purchase: AMAZON MKTPL*NM32N A...,2025.10.14,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/13 AMAZON MKTPL*NM32...,llcBank,2025.10.14_19.47,Expense,NaN
21,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,60.58,NoRcpt Approved Purchase: Harbor Freight Tools U,2025.10.16,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/16 Harbor Freight To...,llcBank,2025.10.16_60.58,Expense,NaN
22,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,57.31,Approved Purchase: SQ *RODCO STEEL DI,2025.10.17,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/16 SQ *RODCO STEEL D...,llcBank,2025.10.17_57.31,Expense,NaN
23,Acct.Cash.Bank,Debit,Acct.Exp.Util,Water,50.00,Pay Monthly Util,2025.10.20,None,None,H_805HighMesa,None,llcBank,BILL PAY Water-COMWSC RECURRING 38 ON 10-20,llcBank,2025.10.20_50.0,Expense,NaN
24,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,36.09,NoRcpt Approved Purchase: WIMBERLEY ACE WIMBER...,2025.10.22,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/22 WIMBERLEY ACE WIM...,llcBank,2025.10.22_36.09,Expense,NaN
25,Acct.Cash.Bank,Debit,Acct.Exp.Repair,Maintenance,135.00,"Repair Utility Outlet,Electrician",2025.10.22,None,None,H_805HighMesa,None,llcBank,VENMO ADDFUNDS 251022 1045679339909 FRANCIS ROJAS,llcBank,2025.10.22_135.0,Expense,NaN
26,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,487.13,Receipt+ Approved Purchase: LAIRD PLASTICS SAN...,2025.11.03,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 10/31 LAIRD PLASTICS SA...,llcBank,2025.11.03_487.13,Expense,NaN
27,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,73.56,NoRcpt Approved Purchase: AMAZON MKTPL*NK5PS A...,2025.11.03,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 11/02 AMAZON MKTPL*NK5P...,llcBank,2025.11.03_73.56,Expense,NaN
28,Acct.Cash.Bank,Debit,Acct.Exp.Other,Plants,42.15,EPay Approved Purchase: SP GROWERS SOLUTIO GRO...,2025.11.07,None,None,H_805HighMesa,None,llcBank,PURCHASE AUTHORIZED ON 11/06 SP GROWERS SOLUTI...,llcBank,2025.11.07_42.15,Expense,NaN
29,Acct.Cash.Bank,Debit,Acct.Exp.Util,Elec,119.49,Pay Monthly Util,2025.11.10,None,None,H_805HighMesa,None,llcBank,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,llcBank,2025.11.10_119.49,Expense,NaN
30,Acct.Cash.Bank,Debit,Acct.Exp.Other,Plants,32.42,EPay Approved Purchase: SP GROWERS SOLUTIO GRO...,2025.11.17,None,None,H_805HighMesa,None,llcBank,PURCHASE AUTHORIZED ON 11/14 SP GROWERS SOLUTI...,llcBank,2025.11.17_32.42,Expense,NaN
31,Acct.Cash.Bank,Debit,Acct.Exp.Other,Const,19.47,NoRcpt Approved Purchase: AMAZON MKTPL*B80W8 A...,2025.11.17,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 11/15 AMAZON MKTPL*B80W...,llcBank,2025.11.17_19.47,Expense,NaN
32,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,30.00,NoRcpt Approved Purchase: HAYS CO TX WIMBER,2025.11.17,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 11/15 HAYS CO TX WIMBER...,llcBank,2025.11.17_30.0,Expense,NaN
33,Acct.Cash.Bank,Debit,Acct.Exp.Other,None,2.00,NoRcpt Approved Purchase: HAYS CO TX WIMBER,2025.11.17,None,None,RV_RV1,None,llcBank,PURCHASE AUTHORIZED ON 11/15 HAYS CO TX WIMBER...,llcBank,2025.11.17_2.0,Expense,NaN
34,Acct.Cash.Bank,Debit,Acct.Exp.Util,Water,50.00,Pay Monthly Util,2025.11.18,None,None,H_805HighMesa,None,llcBank,BILL PAY Water-COMWSC RECURRING 38 ON 11-18,llcBank,2025.11.18_50.0,Expense,NaN
35,Acct.Cash.Bank,Debit,Acct.Exp.Util,Elec,129.16,Pay Monthly Util,2025.12.10,None,None,H_805HighMesa,None,llcBank,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,llcBank,2025.12.10_129.16,Expense,NaN
36,Acct.Cash.Bank,Debit,Acct.Exp.Util,Water,50.00,Pay Monthly Util,2025.12.18,None,None,H_805HighMesa,None,llcBank,BILL PAY Water-COMWSC RECURRING 38 ON 12-18,llcBank,2025.12.18_50.0,Expense,NaN
37,Acct.Cash.Bank,Debit,Acct.Exp.Util,Ins_Home,135.80,Pay Monthly Util,2025.12.26,None,None,H_805HighMesa,None,llcBank,ALLSTATE IND CO INS PYMT DEC024 00000043853221...,llcBank,2025.12.26_135.8,Expense,NaN

In [ ]:
stop

In [ ]:
gl_erDF = erObj.toGL(gl)
gl_aDF = aObj.toGL(gl)
gl_erDF.head(6)



display(Markdown(f"<h3> GL Length - llcExpRev - Records:{len(gl_erDF)}"))
display(gl_erDF.head(6))

display(Markdown(f"<h3> GL Length - llcAssets - Records:{len(gl_aDF)}"))
display(gl_aDF.head(6))

glList = gl.mergeGL([erObj, aObj])
glDF = pd.DataFrame(glList)

display(Markdown(f"<h3> GL Length - New - Records:{len(glDF)}"))
display(glDF.head(4))

<h3> GL Length - llcExpRev - Records:76

,dt,desc,amt,aType,acct,acctSub,propNm,propID,propAddr,propOwners,tID,tDB,refDB,refDoc
0,2025.08.28,Auto: Pay Monthly Util,250.00,Debit,Acct.Exp.Util,Elec,H_805HighMesa,None,None,None,2025.08.28_250.0,llcBank,llcBank,Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...
1,2025.08.28,Auto: Pay Monthly Util,250.00,Credit,Acct.Cash.Bank,Elec,H_805HighMesa,None,None,None,2025.08.28_250.0,llcBank,llcBank,Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...
2,2025.08.28,NoRcp: Approved Purchase: AMAZON MKTPL*6Y5UJ A...,75.76,Debit,Acct.Exp.Other,None,H_805HighMesa,None,None,None,2025.08.28_75.76,llcBank,llcBank,PURCHASE AUTHORIZED ON 08/27 AMAZON MKTPL*6Y5U...
3,2025.08.28,NoRcp: Approved Purchase: AMAZON MKTPL*6Y5UJ A...,75.76,Credit,Acct.Cash.Bank,None,H_805HighMesa,None,None,None,2025.08.28_75.76,llcBank,llcBank,PURCHASE AUTHORIZED ON 08/27 AMAZON MKTPL*6Y5U...
4,2025.09.03,Auto: Pay Monthly Util,150.00,Debit,Acct.Exp.Util,Water,H_805HighMesa,None,None,None,2025.09.03_150.0,llcBank,llcBank,CHECK # 101
5,2025.09.03,Auto: Pay Monthly Util,150.00,Credit,Acct.Cash.Bank,Water,H_805HighMesa,None,None,None,2025.09.03_150.0,llcBank,llcBank,CHECK # 101

<h3> GL Length - llcAssets - Records:26

,dt,desc,amt,aType,acct,acctSub,propNm,propID,propAddr,propOwners,tID,tDB,refDB,refDoc
0,2025.08.20,YR.2025.Begining Balance: Cash,0.00,Debit,Acct.Cash.Bank,None,Cash_LLC,a20250820-Cash1,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250820-Cash1,llcAssets,llcBank,Cash_LLC:llcBank Stmt
1,2025.08.20,YR.2025.Begining Balance: Cash,0.00,Credit,Acct.Equity.Earnings.PnL,None,Cash_LLC,a20250820-Cash1,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250820-Cash1,llcAssets,llcBank,Cash_LLC:llcBank Stmt
2,2025.08.26,Closing: Purchase Property: 805 High Mesa,213936.95,Credit,Acct.Cash.Bank,None,H_805HighMesa,e20250826-805HMD,"805 High Mesa Dr, Wimberley, 78676",{'LLC': 100},a20250826-805HMD,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26
3,2025.08.26,Closing: Purchase Property: 805 High Mesa,213936.95,Debit,Acct.Fixed.Tangible.InService,None,H_805HighMesa,e20250826-805HMD,"805 High Mesa Dr, Wimberley, 78676",{'LLC': 100},a20250826-805HMD,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26
4,2025.08.20,Initial Investment by member,219000.00,Debit,Acct.Cash.Bank,None,H_805HighMesa,e20250826-805HMD,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250826-Cash1,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26
5,2025.08.20,Initial Investment by member,219000.00,Credit,Acct.Equity.Owner.Capital.Funds,None,H_805HighMesa,e20250826-805HMD,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250826-Cash1,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26

Amt is negative llcExpRev 76
---mergeGL: baseObj: llcExpRev  Records:76
Amt is negative llcExpRev 76
---mergeGL: Obj: llcAssets Records:76, Merge:0

<h3> GL Length - New - Records:76

,dt,desc,amt,aType,acct,acctSub,propNm,propID,propAddr,propOwners,tID,tDB,refDB,refDoc,acctType
0,2025.08.28,Auto: Pay Monthly Util,250.00,Debit,Acct.Exp.Util,Elec,H_805HighMesa,None,None,None,2025.08.28_250.0,llcBank,llcBank,Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...,Expense
1,2025.08.28,Auto: Pay Monthly Util,250.00,Credit,Acct.Cash.Bank,Elec,H_805HighMesa,None,None,None,2025.08.28_250.0,llcBank,llcBank,Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...,Asset
2,2025.08.28,NoRcp: Approved Purchase: AMAZON MKTPL*6Y5UJ A...,75.76,Debit,Acct.Exp.Other,None,H_805HighMesa,None,None,None,2025.08.28_75.76,llcBank,llcBank,PURCHASE AUTHORIZED ON 08/27 AMAZON MKTPL*6Y5U...,Expense
3,2025.08.28,NoRcp: Approved Purchase: AMAZON MKTPL*6Y5UJ A...,75.76,Credit,Acct.Cash.Bank,None,H_805HighMesa,None,None,None,2025.08.28_75.76,llcBank,llcBank,PURCHASE AUTHORIZED ON 08/27 AMAZON MKTPL*6Y5U...,Asset

In [7]:
# display total set of acct and Ledger accounts being used
x = erObj.toDF()
erC = list(x.acct.unique()) + list(x.Ledger.unique())

x = aObj.toDF()
aC = list(x.acct.unique()) + list(x.Ledger.unique())

set(erC) & set(aC), set(erC) ^ set(aC),

({'Acct.Cash.Bank', 'Acct.Fixed.Tangible.InService'},
 {'Acct.Equity.Earnings.PnL',
  'Acct.Equity.Owner.Capital.Funds',
  'Acct.Equity.Owner.Cash',
  'Acct.Exp.Depreciation',
  'Acct.Exp.Operating',
  'Acct.Exp.Other',
  'Acct.Exp.Repair',
  'Acct.Exp.Util',
  'Acct.Fixed.Depreciation.Accum',
  'Acct.Fixed.Tangible.InConstruction',
  'Acct.Rev.Fees.Other',
  'Acct.Rev.Other',
  'Acct.Rev.Rent'})

## General Ledger: Incomes/Expenses

In [8]:
# General Ledger - All accounts
from ledger.ledgerGeneral import ledgerGeneral


_IncExpDF = gl.glIncomeExpense(glDF)
display(Markdown(f"<h2> General Ledger: Income Statement (P&L)"))
display(_IncExpDF)

<h2> General Ledger: Income Statement (P&L)

aType                          Credit Debit    Total
acctType acct
Expense  Acct.Exp.Other       1673.02  41.1 -1631.92
         Acct.Exp.Repair        135.0
         Acct.Exp.Util        1056.95
Income   Acct.Rev.Fees.Other   400.53
         Acct.Rev.Rent         4000.0
         Total                 7265.5  41.1  -7224.4

## General Ledger: Balance Sheet

In [9]:
# Generate Balance Sheet
from ledger.ledgerGeneral import ledgerGeneral
_BalShDF = gl.glBalSheet(glDF)
display(Markdown(f"<h2> General Ledger: BalanceSheet"))
display(_BalShDF)

<h2> General Ledger: BalanceSheet

aType                                        Credit      Debit     Total
acctType acct
Asset    Acct.Cash.Bank                   214155.58   226522.5  12366.92
         Acct.Fixed.Tangible.InService               214113.95
Equity   Acct.Equity.Owner.Capital.Funds   219257.0
         Total                            433412.58  440636.45   7223.87

## General Ledger: All transactions

In [10]:
display(Markdown(f"<h2> General Ledger: All"))
sumAll = sumRowCol(gl, glDF.groupby(['acctType', 'acct', 'aType']).amt.sum().unstack().reset_index())
display(sumAll)

<h2> General Ledger: All

NameError: name 'sumRowCol' is not defined

In [ ]:
glDF.sort_values(by='dt')

In [ ]:
STOP Under construction

In [ ]:
# llcAssets.getBalanceSheeet
bsDF = glBalSheet(self, glDF)
bsDF

In [ ]:
t = bsDF.loc['Total']
t.Asset - t.Equity

In [ ]:
# Investment Ledger
import pandas as pd
iDF = llc.bk.df[llc.bk.df.Acct.str.contains('Owner')].copy()
iDF = pd.concat([iDF, llc.bk.df[llc.bk.df.Acct.str.contains('Equity')].copy()])
#iDF = pd.DataFrame(iDF.groupby(['AcctSub','Acct']).amt.sum())
iDF = iDF[['Acct', 'dt', 'amt', 'TDesc', 'AcctSub']].reset_index(drop=True).copy()
iDF.set_index('Acct', drop=True, inplace=True)

# Compute balance : investment/purchases and bank
baliDF = round(iDF.amt.sum(),2)
balBk = round(float(llc.bk.df.amt.sum()),2)

iDF.loc['NetValue YE'] = ['12/31/2025',baliDF,'YE Balance','']
iDF.loc['Gain/Loss YE'] = ['12/31/2025',balBk-baliDF,'Income/Expenses','']
iDF.loc['Acct.Cash.Balance'] = ['12/31/2025',balBk,'YE Cash Balance','']

display(Markdown('<h2> Investment Ledger'))
display(iDF)

# Ledger - Income

In [ ]:
# Investment Ledger
incDF = llc.bk.df[llc.bk.df.Acct.str.contains('.Income')].copy()
incDF = pd.DataFrame(incDF.groupby(['Acct','AcctSub','dt']).amt.sum())

# --- lookup customer name based on ID
cList = llc.customers()
custList = []
for (acct, ndx,dt) in incDF.index:
    for d in cList:
        if d['oID'] == ndx: custList.append(d['nm'])
        else: custList.append('na')
incDF['Customer'] = custList
incDF.loc[('Total','','')] = [incDF.amt.sum(),'']
display(Markdown('<h2> Income Ledger'))
display(incDF)

In [ ]:
# Profit/Loss reconcile with Bank Stmt Balance
df = llc.bk.df.copy()
def _isProfitLoss(self, r):
    if 'Equity' in r.Acct : return 'Equity'
    if r.TransType == 'Exp' : return 'Expense'
    return 'Revenue'

# Classify Transactions into Exp, Rev or False (something else)
df['PnL'] = df.apply(lambda r: _isProfitLoss(llc, r), axis=1)

# Filter only Exp/Rev
plDF = pd.DataFrame(df[df.PnL != 'Equity'])

# Build table subcategories: P&L, Acct and ammount
pvt = pd.pivot_table(plDF, values='amt', index=['PnL', 'Acct'], aggfunc='sum')
pvt.loc[('Total','Profit(Loss)'),'amt'] = round(pvt.amt.sum(),2)
display(Markdown('<h2> Profit/Loss Ledger'))
display(pvt)

In [ ]:
# Subtotal Expenses
expDF = pd.DataFrame(plDF[plDF.PnL == 'Expense'][['Acct','amt']].groupby('Acct').amt.sum())
balExp = round(expDF.amt.sum(),2)
expDF.loc['Subtotal'] = balExp
display(Markdown('<h2> Expense Ledger'))
display(expDF)

In [ ]:
# Subtotal Expenses
revDF = pd.DataFrame(plDF[plDF.PnL == 'Revenue'][['Acct','amt']].groupby('Acct').amt.sum())
balRev = round(revDF.amt.sum(),2)
revDF.loc['Subtotal'] = balRev
display(Markdown('<h2> Revenue: : YE Summary per Account'))
display(revDF)

In [ ]:
# YE Summary : Gains/Loss
display(Markdown("<h2> Revenue: : YE Summary: Gains/Loss"))
pd.DataFrame([['Expense', 'Gains', 'Total Operating Gain/Loss'],
               [balExp, balRev, balRev+balExp]], index=['YE Summary','Amt']).transpose()

In [ ]:
# Expense Ledger
df3 = llc.bk.df
display(Markdown("<h2> Expense Ledger - details"))
df3 = df3[df3.TransType == 'Exp']

pd.DataFrame(df3.groupby(['Acct','AcctSub']).amt.sum())

In [ ]:
# WORK IN PROGRESS - Classify  Expenses
expDF = llc.bk.df[llc.bk.df.Acct.str.contains('Expense')].copy()
df2 = pd.DataFrame(expDF.groupby('AcctSub').amt.sum())
balExp = df2.sum()
df2.loc['Total'] = [balExp]
display(df2)
expDF[['dt', 'amt', 'Acct', 'AcctSub', 'TDesc']]

In [ ]:
# Miscellenous / Unclassified Transactions
display(Markdown("<h2> Ledger - Misc Accounts"))

llc.bk.df[llc.bk.df.Acct.str.contains('Misc')][['dt', 'amt', 'Acct', 'AcctSub', 'desc']]

In [ ]:
aObj = llc.assets()
aObj.fetch()
r = llc.bk.df.iloc[51]
k = aObj._key(r)
print("---", k, "<<<")
aObj._matchBk(r)
i = aObj.kDict[k[0]]
aObj.df.iloc[i]

In [ ]:
# Owners DB
display(Markdown("<h2> llcOwners DB"))

pd.DataFrame(llc.owners())

In [ ]:
# Customer DB
display(Markdown("<h2> llcCustomers DB"))
pd.DataFrame(llc.customers())

In [ ]:
# Asset DB
from ledger.llcAssets import llcAssets

a = llcAssets(llc)
a.fetch()


display(Markdown("<h2> llcAsset DB"))
a.df

# Accounting-Bookkeeping 101

## accounting ledgers: 

| Ledger | Description |
| :---- | :----: |
|General Ledger | master document; record all transactions; includes all accounts related to a company's assets, liabilities, equity, revenue, and expenses.|
|Sales Ledger | |
|Purchase Ledger |  

## Key Principles (pyApps)

- utilizing pythn accounting libraries
- double-entry bookkeeping, or by
- building a custom application (general ledger for rental LLC)
- a web framework / command-line tool
- read bank statements (often from CSV files)
- perform transactions and reporting. 

### Beancount: 
A Python package for double-entry accounting. You can use its command-line tools to manage financial transactions written in a plain-text file, making it suitable for tracking an LLC's finances and maintaining a Git-based audit trail.
### Blnk Finance: 
An open-source, developer-focused toolkit that includes a double-entry ledger for managing balances and transactions. It offers features like balance monitoring, reconciliation, and identity management, and is designed to help you build fintech products.
### Django Ledger: 
An open-source accounting and financial ledger system built on the Django framework. It's a good option if you need to integrate robust accounting features directly into a Python web application. 

### Github Py Ledgers

1. [**>Confidential Ledger Azure**](https://learn.microsoft.com/en-us/python/api/overview/azure/confidentialledger-readme?view=azure-python#key-concepts)
    - good reference
1. [**> Ledger Visualization**](https://wilw.dev/blog/2022/04/24/ledger-python-visualisation/) : pure text (csv) files, uses vis.py

## Ledger for Taxes

- bare minimum records
- accounting ledger for an LLC to file taxes
- clear, accurate summary
  - all business income (gross receipts)
  - expenses.
- no specific bookkeeping method
- method used must clearly reflect your income and expenses. 

## key information required for each transaction includes:

- Amount of the transaction.
- Date of the transaction.
- Description of the item purchased or service received.
- Business purpose (why the expense was necessary).
- Source of income or the payee for expenses. 
- Essential Records and Documentation

## Documentation
The IRS requires that you maintain documentation to support the figures reported on your tax return. 

- Well-organized,
- detailed records make tax preparation easier
- help you maximize deductions
- ensuring you have the necessary documentation in case of an IRS audit.
- Records: keep at least three years from the date you filed the return. 


|Record Type 	|Description	|Supporting Documents to Keep|
| ---- | ---- | ---- |
|Income	|All gross receipts from business operations.	|Invoices sent to clients, cash register tapes, deposit slips, bank account deposits, and Forms 1099-NEC received.
|Expenses	|All costs incurred to carry on your business.|	Canceled checks, credit card statements, invoices for purchases, and receipts.|
|Assets & Depreciation|	Records for property like equipment or vehicles used in the business that last more than a year.	|Date and method of acquisition, purchase price, cost of improvements, deductions taken for depreciation, business use, and details of disposition/sale.|
|Payroll (if applicable)|	Records related to employees (not owners, typically).|	Annual W-2s, quarterly and annual payroll tax returns, and complete pay records/time sheets for each employee.|

### Multi-member LLC: Filing Requirements by LLC Structure
- Your LLC's tax classification determines which forms you will need to file, which impacts how you report your income and expenses. 
- Multi-member LLC: The default is to be taxed as a partnership. The LLC files an informational Form 1065 and provides a Schedule K-1 to each member, who then reports their share of profit or loss on their personal Form 1040 using Schedule E.
- LLC taxed as a Corporation (S corp or C corp): If you elect this status, you will file Form 1120 (C corp) or Form 1120-S (S corp).

# Accounting: Best Practices

## Rental Accounting

|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|Acct.Cash.Income     | ##.## |       | yy.mm.dd | CustID  | record the cash received |
|Acct.Rent.Receivable | ##.## |       | yy.mm.dd | CustID  | record amt owed by the tenant|
|Income.Rent.Revenue  |       | ##.## | yy.mm.dd | CustID  | record total income earned, period |

## Initial investment of cash
|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|Acct.Cash.Investment |       | ##.## | yy.mm.dd |           | record cash investment|
|LLC.Equity.Member    | ##.## |       | yy.mm.dd | memberID  | LLC equity, member % |

## Company purchasing an investment
|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|LLC.Prop.Investment  | ##.## |        | yy.mm.dd | propID | record value of purchase/investment|
|Acct.Cash.Purchase   |       | ##.##  | yy.mm.dd | propID | Cash account reduced |

## Expense: Paid by Cash / Debit Card
|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|Acct.Cash.Expense    |       | ##.##  | yy.mm.dd | expCls | record expense details|
|Acct.Expense.<expCls>| ##.## |        | yy.mm.dd | expCls | record expense details|


## Expense: Paid by accured (credit card/loan-agreement/late payment)
|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|Liab.Payable.Expense |       | ##.## | yy.mm.dd | expCls | record expense details |
|Liab.Expense.<expCls>| ##.## |       | yy.mm.dd | expCls | record expense details|
| | | | | | future |
|Acct.Cash.Expense    |       | ##.## | yy.mm.dd | expCls | record expense details|
|Acct.Expense.<expCls>| ##.## |       | yy.mm.dd | expCls | record expense details|


Example: Recording rent expense Transaction: A company pays \(\$1,000\) for monthly rent.Debit: The Rent Expense account is debited for \(\$1,000\).Credit: The Cash account is credited for \(\$1,000\). 

Note 3Example: Recording an accrued expense Transaction: At the end of the month, a company has an accrued electricity expense of \(\$300\) that has not yet been paid.Debit: The Electricity Expense account is debited for \(\$300\).Credit: The Accrued Expenses (or Electricity Expense Payable) account is credited for \(\$300\) to create the liability. 


## NOTE 1: Subsequent changes to the investment
- accounting for an investment becomes more complex, 
- value of investment fair value method or equity method,
- depending on the type of investment.

## NOTE 2: Earnings from investments
- recognized in the `income statement`
- dividends received are often treated as either operating or investment inflows
- `cash flow statement`.

## NOTE 3: accrual method
- expenses are recorded when they are incurred, not when they are paid.
- Example: Recording an accrued expense Transaction:
    - end of the month, not paid elect expense 
    - a company has an accrued electricity expense of $300
    - Debited $300 :  Expense.Utility.Elec
    - Credit $300 : Liab.Expense.Utility
    - The Accrued Expenses (or Electricity Expense Payable) - create the liability.
    - 
## NOTE 4: Investments on form 1065
- An LLC taxed as a partnership records owner investments (`capital contributions`) on IRS Form 1065,
- primarily on `Schedule L (Balance Sheets per Books)` and
- Schedule M-2 (Analysis of Partners' Capital Accounts).
- Investments are considered `capital contributions` rather than income
- Capital contributions are tracked to determine the partners' basis in the LLC